# -*- coding: utf-8 -*-
"""Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hv6JP9DwDtBtMfabXe2z4-J1_RL80k4_

# **4-1 문자열**
"""

sentence='나는 소년입니다.'
print(sentence)
sentence2="파이썬은 쉬워요"
print(sentence2)
sentence3="""
나는 소년이고,
파이썬은 쉬워요
"""
print(sentence3)

"""# **4-2 슬라이싱**"""

from google.colab import drive
drive.mount('/content/drive')

jumin="961016-1234567"

print("성별 : "+ jumin[7])
print("연 : "+jumin[0:2]) # 0 부터 2 직전까지(0~1)
print("월 : "+jumin[2:4])
print("일 : "+jumin[4:6])

print("생년월일 : "+jumin[:6]) #처음부터 6직전까지
print("뒤 7자리 : "+jumin[7:]) #처음부터 끝까지
print("뒤 7차리(뒤에서부터) : "+jumin[-7:]) #맨 뒤에서 7번째부터 끝까지

"""# **4-4 문자열 포맷**

%d = 정수값

%s = 문자열

%c = 문자(1글자)

{ } .foramt
"""

#방법1
print("나는 %d 살입니다." %20)
print("나는 %s을 좋아해요"%"파이썬")
print("Apple은 %c로 시작해요"%"A")
print("나는 %s색과 %s색을 좋아해요."%("파란","빨간"))

#방법2
print("나는 {}살입니다.".format(20))
print("나는 {}색과 {}색을 좋아해요".format("파란","빨간"))
print("나는 {0}색과 {1}색을 좋아해요".format("파란","빨간"))
print("나는 {1}색과 {0}색을 좋아해요".format("파란","빨간"))

#방법3
print("나는 {age}살이며, {color}색을 좋아해요".format(age=20, color="빨간"))

#방법4
age = 20
color="빨간"
print(f"나는 {age}살이며, {color}색을 좋아해요")

"""# **4-3 문자열 처리 함수**


lower() = 소문자

upper() = 대문자

isupper() = 대문자인지 확인

len() = 길이 구하기

index() = 위치 구하기 (없으면 에러)

find() = 원하는 값 찾기(없으면 -1 반환)

count() = 원하는 값 몇개 있는지

"""

python = "Python is Amazing"
print(python.lower())
print(python.upper())
print(python[0].isupper())
print(len(python))
print(python.replace("Python","Java"))

index = python.index("n")
print(index)
index =python.index("n",index+1)
print(index)

print(python.find("Java"))

print(python.count("n"))